export const mockUser = {
    login: 'samazevedo',
    id: 34683893,
    node_id: 'MDQ6VXNlcjM0NjgzODkz',
    avatar_url: 'https://avatars.githubusercontent.com/u/34683893?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/samazevedo',
    html_url: 'https://github.com/samazevedo',
    followers_url: 'https://api.github.com/users/samazevedo/followers',
    following_url:
        'https://api.github.com/users/samazevedo/following{/other_user}',
    gists_url: 'https://api.github.com/users/samazevedo/gists{/gist_id}',
    starred_url:
        'https://api.github.com/users/samazevedo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/samazevedo/subscriptions',
    organizations_url: 'https://api.github.com/users/samazevedo/orgs',
    repos_url: 'https://api.github.com/users/samazevedo/repos',
    events_url: 'https://api.github.com/users/samazevedo/events{/privacy}',
    received_events_url:
        'https://api.github.com/users/samazevedo/received_events',
    type: 'User',
    site_admin: false,
    name: 'Sam Azevedo',
    company: null,
    blog: 'www.samazevedo.com',
    location: 'Sao Paulo',
    email: null,
    hireable: true,
    bio: 'Frontend Web Developer ',
    twitter_username: 'SamAzevedo4',
    public_repos: 50,
    public_gists: 0,
    followers: 0,
    following: 2,
    created_at: '2017-12-19T14:06:39Z',
    updated_at: '2022-06-17T00:09:14Z',
}
